### ISSUE TITLE
Uniprot description NULL

### ISSUE THREAD

**Issue by sajmmon** [PathwayCommons/pcviz#13]
Hi,
I just set up PCviz as described in README.md and after copying war to Tomcat I see Error is catalina.out:

java.io.FileNotFoundException: http://www.uniprot.org/uniprot/null.txt

Please let me know how to update pcviz.properties

**Comment by armish** [comment]
Hi @sajmmon, I am so sorry to reply this late, but this apparently slipped through the cracks. Let me know if you still have issues with this and we will be happy to help.

**Comment by IgorRodchenkov** [comment]
I fixed that yesterday too
