### ISSUE TITLE
uniprot_scraper.sh error (cannot calculate network neighborhoods for each gene)

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pcviz#21]
Having a fresh (with the cache folders all empty) local pcviz instance accordingly configured (connects to pathwaycommons.baderlab.org/ PC2 server), up and running, I run the uniprot_scraper.sh script (after properly updating the pcviz URL in uniprot_scraper.js, etc.) and immediately got error like:

events.js:72
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
  at errnoException (net.js:905:11)
  at Object.afterWrite (net.js:721:19)
- happens shortly after it started (and after the intermediate uniprot ids.txt file first got successfully created from the hgnc.txt; so, seems, it’s 'phantomjs uniprot_scraper.js' process where  the error happens). The process exited after only one UniProt ID was processed and .json and .png file created in the output dir... no other errors logged, except that I got some info in the log file. 
  So, here is what I did and more what I got (username removed):

MacPro7:scripts$ sh uniprot_scraper.sh ~/pcviz/data/hgnc.txt ids.txt output log.log

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
MacPro7:scripts rodche$ ll
total 51880
-rw-r--r--  1 328 29 Jan 11:53 crop_canvas.sh
-rw-r--r--  1 1792 29 Jan 11:53 extract_uniprot.js
-rw-r--r--  1 788  1 Mar 13:05 log.log
-rw-------  1 26540657  1 Mar 13:05 nohup.out
drwxr-xr-x  4 136  1 Mar 13:05 output
-rw-r--r--  1 3469 29 Feb 18:01 uniprot_scraper.js
-rw-r--r--  1 408 29 Feb 19:42 uniprot_scraper.sh
MacPro7:scripts$ ll output/
total 488
-rw-r--r--  1 rodche  staff   48706  1 Mar 13:05 P04217.json
-rw-r--r--  1 rodche  staff  199403  1 Mar 13:05 P04217.png
MacPro7:scripts rodche$ cat log.log 
fetchNHood(): P04217
NODE_POSITION__{"x":938.0097805116003,"y":148.97475304266862}
NODE_POSITION__{"x":330.9112756593834,"y":855.4722770660128}
NODE_POSITION__{"x":217.8574538462652,"y":764.1524834972984}
NODE_POSITION__{"x":217.8574538462652,"y":764.1524834972984}
NODE_POSITION__{"x":157.401552395857,"y":704.297329928565}
NODE_POSITION__{"x":154.53245241641645,"y":667.9672335590492}
NODE_POSITION__{"x":154.6078407056945,"y":606.3462629632237}
NODE_POSITION__{"x":106.51614971048424,"y":525.8460214520969}
NODE_POSITION__{"x":50,"y":466.65371030118314}
NODE_POSITION__{"x":50,"y":466.65371030118314}
NODE_POSITION__{"x":50,"y":466.65371030118314}
NODE_POSITION__{"x":50,"y":466.65371030118314}
NODE_POSITION__{"x":50,"y":466.65371030118314}
fetchNHood(): 7
[timeout] skipping query 7
MacPro7:scripts$

**Comment by armish** [comment]
closed via https://github.com/PathwayCommons/pcviz/commit/0c0f413b3573933c0e562ae0aae8df6e47160f59
