### ISSUE TITLE
Query/network processing begins too soon and gets unwanted intermediate results.

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pcviz#26]
PCViz query/network processing begins too early - as user adds gene symbols.
This no good. Often, this is actually waste of resources and user's patience.
For example, I am going to use three gene names, and want to add them one by one (perhaps, I'd like to double-check the third gene symbol and need some time, or got distracted, etc...).
I do NOT want to see (and wait for) the network after I typed in the first or second gene name; this is wasting of time and resources. I only want to see the network after all the three genes added.

So, there either should be a button to press, or a reasonable interval (e.g., 10 sec) of user inactivity (in the input field), or loss of focus before the request is sent to the servers and network starts to build.

Attn.: @armish @onursumer

**Comment by armish** [comment]
Igor, we do have [a timeout of 5 seconds](https://github.com/PathwayCommons/pcviz/blob/master/src/main/webapp/js/components/pcviz.network.js#L200); but, if feels too short, happy to bump it to ~10 seconds. I don't like the idea of having a submit button as it clutters the supposedly minimal UI, but also don't have any strong opinions against having it there as long as we tweak the design to accommodate that. 

This is one of those we-need-to-survey-users-to-find-the-right-settings features.

**Comment by IgorRodchenkov** [comment]
Increasing the delay (see the changeset) did not work; need to fix somewhere else... We probably want a push button there to submit a new user query. But if the URL (HTTP GET request) contains a list of IDs, such as /pcviz/#neighborhood/MDM2, then it should run the query and start building a network right away.

**Comment by armish** [comment]
Igor, this is my bad. Apparently I pointed the wrong the timeout event to you. The correct timer is this one: https://github.com/PathwayCommons/pcviz/blob/master/src/main/webapp/js/components/pcviz.home.js#L48 (in pcviz.home.js, see the waitTime variable). Bumping this further up should do the trick.
