### ISSUE TITLE
Context cannot be loaded.

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pcviz#32]
Cannot load a cancer study (using the Context tab); it takes forever, loading....

**Comment by IgorRodchenkov** [comment]
This is issue for both old PCViz (at pathwaycommons.org/pcviz/ and sanderlab.org/pcviz/) and new (at beta.pathwaycommons.org/pcviz/) instances. 
@armish  @cannin @gbader  @emekdemir @onursumer @ozgunbabur @jvwong 
Shall we fix or remove the entire feature?

**Comment by armish** [comment]
looks like "some" people are trying to use that functionality:

![pcviz context tab](http://f.cl.ly/items/141Z392T0g432V132n1S/Image%202016-04-15%20at%203.16.13%20PM.png)

Is it something we can debug, Igor? What does the server log say? Maybe it is just a minor fix?

**Comment by IgorRodchenkov** [comment]
@armish @ozgunbabur 

PCViz depends on org.cbio:causality:1.0.1-SNAPSHOT from the biopax.org/m2repo/snapshots repository (perhaps not the latest snapshot).

After opening BRCA1 neighborhood network in the PCViz, trying to load "Acinar cell carcinoma... " cancer context, which never ends,.. got (can see) the following in the Chrome Developer Tools window, Console -

Failed to load resource: the server responded with a status of 400 (Bad Request)
http://beta.pathwaycommons.org/pcviz/cancer/context/paac_jhu_2014/mutation/MDC1,ATF2,CCNK,MI0002468,..,SYCP3,MIMAT0000456
(I replaced many IDs with ... above)
...
I kept experimenting, and found that this query works: http://beta.pathwaycommons.org/pcviz/cancer/context/paac_jhu_2014/mutation/MDC1,ATF2,CCNK
but this:
http://beta.pathwaycommons.org/pcviz/cancer/context/paac_jhu_2014/mutation/MDC1,ATF2,CCNK,MIMAT0000456
- fails - returns error 400. 

Apparently, it's there - 
https://github.com/PathwayCommons/pcviz/blob/master/src/main/java/org/pathwaycommons/pcviz/controller/CancerController.java#L89
that _cancerContextService.loadContext(..)_ method throws an exception - it dislikes MAT\* IDs ;)

It should simply ignore unknown IDs instead.
So, I'll fix by, at least, catching the exception, skipping the "unknown" ID...
